-- AlterTable
ALTER TABLE `Record` ADD COLUMN `assigned` VARCHAR(191) NULL,
    ADD COLUMN `begin` DATETIME(3) NULL,
    ADD COLUMN `dueDate` DATETIME(3) NULL,
    ADD COLUMN `end` DATETIME(3) NULL,
    ADD COLUMN `previewEnd` DATETIME(3) NULL,
    ADD COLUMN `previewStart` DATETIME(3) NULL,
    ADD COLUMN `time` VARCHAR(191) NULL,
    ADD COLUMN `timeBegin` DATETIME(3) NULL,
    ADD COLUMN `timeEnd` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `Task` ADD COLUMN `assigned` VARCHAR(191) NULL,
    ADD COLUMN `begin` DATETIME(3) NULL,
    ADD COLUMN `dueDate` DATETIME(3) NULL,
    ADD COLUMN `end` DATETIME(3) NULL,
    ADD COLUMN `previewEnd` DATETIME(3) NULL,
    ADD COLUMN `previewStart` DATETIME(3) NULL,
    ADD COLUMN `time` VARCHAR(191) NULL,
    ADD COLUMN `timeBegin` DATETIME(3) NULL,
    ADD COLUMN `timeEnd` DATETIME(3) NULL;
