prisma:
	## Criacao de Migracoes de Base de Dados
	npx prisma migrate dev

	## execucao de alteracoes
	npx prisma db pull
	
	## execucao do seed
	npx prisma db seed

	## Visualizacao grafica
	npx prisma studio